server:
    port: 9192
    
    servlet:
      context-path: /

spring:
    application: 
        name: msplayer
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/msplayer
        username: root
        password: Nguyenleviz@311
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQLDialect
    # Cau hinh CORS
#    web:
#      cors:
#          allowed-origins: http://localhost:3000